const {chromium}=require('C:/Users/7jkha/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.join(__dirname,'..');
const sdk={app:'export const getApps=()=>[];export const initializeApp=()=>({});',auth:`export const auth={currentUser:null};export const getAuth=()=>auth;export const browserLocalPersistence={};export const setPersistence=async()=>{};export class GoogleAuthProvider{setCustomParameters(){} addScope(){} static credentialFromResult(){return {accessToken:'test'}}}export const signInWithPopup=async()=>window.testAuth({uid:'unpaid'});export const signOut=async()=>window.testAuth(null);export const deleteUser=async()=>window.testAuth(null);export const reauthenticateWithPopup=async()=>({});export const onAuthStateChanged=(a,cb)=>{window.testAuth=u=>{a.currentUser=u;cb(u)};window.testAuth(null)};`,firestore:`export const getFirestore=()=>({});export const doc=()=>({});export const onSnapshot=(r,o,cb)=>{window.testPurchase=paid=>cb({exists:()=>true,data:()=>({paid}),metadata:{fromCache:false,hasPendingWrites:false}});return ()=>{}};`};
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{for(const width of [390,1440]){const p=await b.newPage({viewport:{width,height:900}});const errors=[],reads=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://www.gstatic.com/firebasejs/**',r=>{const name=r.request().url().match(/firebase-(app|auth|firestore)\.js/)[1];reads.push(name);return r.fulfill({contentType:'text/javascript',body:sdk[name]})});await p.route('https://9board.jp/**',r=>{let file=path.join(root,new URL(r.request().url()).pathname);if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');return fs.existsSync(file)?r.fulfill({path:file}):r.fulfill({status:404,body:''})});
await p.goto('https://9board.jp/mobile/free/#matches',{waitUntil:'networkidle'});const f=p.frames().find(f=>f.url().includes('/mobile/free/app.html'));assert(f);await f.waitForFunction(()=>window.NineBoardAuth);assert.equal(await f.evaluate(()=>document.documentElement.classList.contains('nineboard-authenticated')),true);assert(!reads.includes('firestore'));assert.equal(await f.evaluate(()=>NineBoardPlan.canAddLocalLayout(1000)&&NineBoardPlan.canAddMatchRecord(1000)&&NineBoardPlan.can('layoutMatchLink')),true);
await f.evaluate(()=>{localStorage.setItem('9b_matches',JSON.stringify(Array.from({length:11},(_,i)=>({id:i,title:'記録'+i,date:'2026-10-10'}))));dispatchEvent(new Event('9board:datachange'))});await f.locator('#newMatchText').click();await f.locator('#matchDate').fill('2026-10-10');await f.locator('#matchTitle').fill('無料の追加');await f.locator('#matchForm button[type=submit]').click();assert.equal(await f.evaluate(()=>JSON.parse(localStorage.getItem('9b_matches')).length),12);
await f.evaluate(()=>NineBoardAuth.signIn());assert.equal(await f.evaluate(()=>NineBoardAuthUser.uid),'unpaid');await f.evaluate(()=>NineBoardAuth.signOut());assert.equal(await f.evaluate(()=>document.documentElement.classList.contains('nineboard-authenticated')),true);assert.equal(await f.evaluate(()=>JSON.parse(localStorage.getItem('9b_matches')).length),12);
await f.evaluate(()=>location.hash='home');await f.locator('#ballbar button').nth(2).click();assert(await f.locator('#ballsLayer .ball').count()>0);await p.screenshot({path:path.join(root,'../mobile-free-'+width+'.png')});assert.deepEqual(errors,[]);await p.goto('https://9board.jp/mobile/',{waitUntil:'networkidle'});const paid=p.frames().find(f=>f.url().includes('/Billiards_layout_mobile/'));await paid.waitForFunction(()=>window.testAuth);assert.equal(await paid.evaluate(()=>document.documentElement.classList.contains('nineboard-authenticated')),false);await paid.evaluate(()=>testAuth({uid:'paid-user'}));await paid.evaluate(()=>testPurchase(true));assert.equal(await paid.evaluate(()=>document.documentElement.classList.contains('nineboard-authenticated')),true);await paid.evaluate(()=>testPurchase(false));assert.equal(await paid.evaluate(()=>document.documentElement.classList.contains('nineboard-authenticated')),false);console.log('PASS free and paid',width);await p.close()}}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
