(()=>{"use strict";
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const store={get(k,d=[]){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),1300)};
function go(name){$$(".screen").forEach(s=>s.classList.toggle("active",s.dataset.screen===name));$$(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.to===name));$("#appView").scrollTo({top:0});if(name==="home")renderHome()}
$$("[data-to],.jump").forEach(b=>b.addEventListener("click",()=>go(b.dataset.to)));

const colors={1:"#edbb22",2:"#113d9c",3:"#a91f16",4:"#dc4438",5:"#e9681f",6:"#00583b",7:"#76501b",8:"#171a18",9:"#edbb22",10:"#113d9c",11:"#a91f16",12:"#dc4438",13:"#e9681f",14:"#00583b",15:"#76501b"};
const felt=$("#felt"),svg=$("#svgLayer"),ballsLayer=$("#ballsLayer"),notesLayer=$("#notesLayer"),tableViewport=$("#tableViewport"),tableStage=$("#tableStage");
const aim=$("#aimGuide"),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let tool="move",balls=[],lines=[],memos=[],history=[],future=[],drawing=null,drag=null;
function snapshot(){return JSON.stringify({balls,lines,memos})}
function commit(){history.push(snapshot());if(history.length>50)history.shift();future=[]}
function restore(raw){if(!raw)return;const s=JSON.parse(raw);balls=s.balls||[];lines=s.lines||[];memos=s.memos||[];renderLayout()}
commit();
function undo(){if(history.length<=1)return;future.push(history.pop());restore(history.at(-1));toast("1つ戻しました")}
function redo(){if(!future.length)return;const x=future.pop();history.push(x);restore(x);toast("1つ進みました")}
$("#undoBtn").onclick=$("#undoTop").onclick=undo;$("#redoBtn").onclick=$("#redoTop").onclick=redo;

function showAim(e){const r=felt.getBoundingClientRect();aim.style.setProperty("--x",clamp((e.clientX-r.left)/r.width*100,0,100)+"%");aim.style.setProperty("--y",clamp((e.clientY-r.top)/r.height*100,0,100)+"%");aim.classList.add("visible")}
function hideAim(){aim.classList.remove("visible")}
function point(e){const r=felt.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width*100,1,99),y:clamp((e.clientY-r.top)/r.height*100,2,98)}}

const zoom={scale:1,min:1,max:3,tx:0,ty:0};
function clampPan(){if(zoom.scale<=1){zoom.tx=0;zoom.ty=0;return}const r=tableViewport.getBoundingClientRect(),mx=r.width*(zoom.scale-1)/2,my=r.height*(zoom.scale-1)/2;zoom.tx=clamp(zoom.tx,-mx,mx);zoom.ty=clamp(zoom.ty,-my,my)}
function applyZoom(){clampPan();tableStage.style.transform=`translate(${zoom.tx}px,${zoom.ty}px) scale(${zoom.scale})`}
function setZoom(next,cx,cy){const old=zoom.scale,n=clamp(next,zoom.min,zoom.max);if(cx!=null&&cy!=null&&n!==old){const r=tableViewport.getBoundingClientRect(),dx=cx-(r.left+r.width/2)-zoom.tx,dy=cy-(r.top+r.height/2)-zoom.ty,k=n/old;zoom.tx-=dx*(k-1);zoom.ty-=dy*(k-1)}zoom.scale=n;if(n===1){zoom.tx=0;zoom.ty=0}applyZoom()}
function adjustZoom(d){const r=tableViewport.getBoundingClientRect();setZoom(zoom.scale+d,r.left+r.width/2,r.top+r.height/2)}
$("#zoomIn").onclick=()=>adjustZoom(.2);$("#zoomOut").onclick=()=>adjustZoom(-.2);$("#zoomReset").onclick=()=>{setZoom(1);toast("拡大をリセットしました")};
let pinch=null;
const dist=t=>Math.hypot(t[0].clientX-t[1].clientX,t[0].clientY-t[1].clientY),center=t=>({x:(t[0].clientX+t[1].clientX)/2,y:(t[0].clientY+t[1].clientY)/2});
tableViewport.addEventListener("touchstart",e=>{if(e.touches.length===2){pinch={d:dist(e.touches),s:zoom.scale};hideAim()}},{passive:false});
tableViewport.addEventListener("touchmove",e=>{if(e.touches.length===2&&pinch){e.preventDefault();const c=center(e.touches);setZoom(pinch.s*dist(e.touches)/pinch.d,c.x,c.y)}},{passive:false});
const endPinch=e=>{if(!e.touches||e.touches.length<2)pinch=null};tableViewport.addEventListener("touchend",endPinch);tableViewport.addEventListener("touchcancel",endPinch);

function ballClass(n){return "ball "+(n===0?"cue":n<=8?"solid":"stripe")}
function renderLines(){svg.innerHTML="";const ns="http://www.w3.org/2000/svg";for(const l of lines){if(l.type==="arrow"){const defs=document.createElementNS(ns,"defs"),marker=document.createElementNS(ns,"marker"),path=document.createElementNS(ns,"path"),id="a"+String(l.id).replace(/\W/g,"");marker.id=id;marker.setAttribute("viewBox","0 0 10 10");marker.setAttribute("refX","8");marker.setAttribute("refY","5");marker.setAttribute("markerWidth","5");marker.setAttribute("markerHeight","5");marker.setAttribute("orient","auto");path.setAttribute("d","M0 0 L10 5 L0 10 z");path.setAttribute("fill","#fff");marker.appendChild(path);defs.appendChild(marker);svg.appendChild(defs);l._marker=id}const el=document.createElementNS(ns,"line");for(const [k,v] of [["x1",l.x1+"%"],["y1",l.y1+"%"],["x2",l.x2+"%"],["y2",l.y2+"%"],["stroke","#fff"],["stroke-width","2"],["stroke-linecap","round"]])el.setAttribute(k,v);if(l._marker)el.setAttribute("marker-end",`url(#${l._marker})`);svg.appendChild(el)}}
function renderLayout(){ballsLayer.innerHTML="";notesLayer.innerHTML="";renderLines();for(const b of balls){const el=document.createElement("div");el.className=ballClass(b.n);el.dataset.id=b.id;el.style.left=b.x+"%";el.style.top=b.y+"%";if(b.n)el.style.setProperty("--ball-color",colors[b.n]);const sp=document.createElement("span");sp.textContent=b.n||"";el.appendChild(sp);el.addEventListener("pointerdown",ballDown);ballsLayer.appendChild(el)}for(const m of memos){const el=document.createElement("div");el.className="table-memo";el.dataset.id=m.id;el.style.left=m.x+"%";el.style.top=m.y+"%";el.textContent=m.text;el.addEventListener("pointerdown",memoDown);notesLayer.appendChild(el)}}
function addBall(n,p){const base=p||{x:n===0?22:65+(n%5)*4,y:40+(n%4)*7};balls.push({id:crypto.randomUUID?.()||Date.now()+Math.random(),n,x:base.x,y:base.y});commit();renderLayout()}
function shiftAll(dx,dy){balls.forEach(o=>{o.x=clamp(o.x+dx,1,99);o.y=clamp(o.y+dy,2,98)});memos.forEach(o=>{o.x=clamp(o.x+dx,1,99);o.y=clamp(o.y+dy,2,98)});lines.forEach(l=>{l.x1=clamp(l.x1+dx,0,100);l.y1=clamp(l.y1+dy,0,100);l.x2=clamp(l.x2+dx,0,100);l.y2=clamp(l.y2+dy,0,100)})}
function beginAll(e){drag={kind:"all",last:point(e)};felt.setPointerCapture?.(e.pointerId);e.preventDefault();showAim(e)}
function ballDown(e){e.stopPropagation();const id=e.currentTarget.dataset.id;if(tool==="erase"){balls=balls.filter(x=>x.id!==id);commit();renderLayout();return}const o=balls.find(x=>x.id===id);if((tool==="line"||tool==="arrow")&&o){drawing={id:Date.now()+Math.random(),type:tool,x1:o.x,y1:o.y,x2:o.x,y2:o.y};felt.setPointerCapture?.(e.pointerId);showAim(e);e.preventDefault();return}if(tool==="moveall"){beginAll(e);return}if(tool!=="move")return;drag={kind:"ball",id};e.currentTarget.setPointerCapture?.(e.pointerId);showAim(e);e.preventDefault()}
function memoDown(e){e.stopPropagation();const id=e.currentTarget.dataset.id;if(tool==="erase"){memos=memos.filter(x=>x.id!==id);commit();renderLayout();return}if(tool==="moveall"){beginAll(e);return}if(tool!=="move")return;drag={kind:"memo",id};e.currentTarget.setPointerCapture?.(e.pointerId);e.preventDefault()}
document.addEventListener("pointermove",e=>{if(!drag)return;const p=point(e);if(drag.kind==="all"){shiftAll(p.x-drag.last.x,p.y-drag.last.y);drag.last=p;renderLayout();showAim(e);return}const arr=drag.kind==="ball"?balls:memos,o=arr.find(x=>x.id===drag.id);if(!o)return;o.x=p.x;o.y=p.y;renderLayout();if(drag.kind==="ball")showAim(e)},{passive:false});
document.addEventListener("pointerup",()=>{if(drag){drag=null;hideAim();commit()}});document.addEventListener("pointercancel",()=>{drag=null;hideAim()});
felt.addEventListener("pointerdown",e=>{if(e.target!==felt&&e.target!==svg)return;const p=point(e);if(tool==="line"||tool==="arrow"){drawing={id:Date.now()+Math.random(),type:tool,x1:p.x,y1:p.y,x2:p.x,y2:p.y};felt.setPointerCapture?.(e.pointerId);showAim(e)}else if(tool==="memo"){const text=prompt("メモを入力");if(text){memos.push({id:Date.now()+Math.random(),text,x:p.x,y:p.y});commit();renderLayout()}}else if(tool==="moveall")beginAll(e)});
felt.addEventListener("pointermove",e=>{if(!drawing)return;const p=point(e);drawing.x2=p.x;drawing.y2=p.y;showAim(e);const tmp=[...lines,drawing];const old=lines;lines=tmp;renderLines();lines=old});
felt.addEventListener("pointerup",()=>{if(drawing){lines.push(drawing);drawing=null;commit();renderLayout()}hideAim()});
felt.addEventListener("pointercancel",()=>{drawing=null;renderLayout();hideAim()});

const ballbar=$("#ballbar");
for(let n=0;n<=15;n++){const b=document.createElement("button"),m=document.createElement("div");m.className="palette-ball "+(n===0?"cue":n<=8?"solid":"stripe");if(n)m.style.setProperty("--ball-color",colors[n]);const s=document.createElement("span");s.textContent=n||"";m.appendChild(s);b.appendChild(m);let start=null,preview=null;b.addEventListener("pointerdown",e=>{start={x:e.clientX,y:e.clientY,moved:false};b.setPointerCapture?.(e.pointerId);e.preventDefault()});b.addEventListener("pointermove",e=>{if(!start)return;if(!start.moved&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>5){start.moved=true;preview=m.cloneNode(true);preview.style.position="fixed";preview.style.zIndex="999";preview.style.pointerEvents="none";preview.style.left=e.clientX+"px";preview.style.top=e.clientY+"px";document.body.appendChild(preview)}if(start.moved){preview.style.left=e.clientX+"px";preview.style.top=e.clientY+"px";showAim(e)}});const end=(e,cancel=false)=>{if(!start)return;const moved=start.moved;preview?.remove();preview=null;start=null;hideAim();if(cancel)return;const r=felt.getBoundingClientRect();if(moved&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)addBall(n,point(e));else if(!moved)addBall(n)};b.addEventListener("pointerup",e=>end(e));b.addEventListener("pointercancel",e=>end(e,true));ballbar.appendChild(b)}
$$(".tool[data-tool]").forEach(b=>b.onclick=()=>{$$(".tool[data-tool]").forEach(x=>x.classList.remove("active"));b.classList.add("active");tool=b.dataset.tool});
$("#clearLayout").onclick=()=>{if(confirm("配置をリセットしますか？")){balls=[];lines=[];memos=[];commit();renderLayout();setZoom(1)}};
$("#saveLayout").onclick=()=>{const title=prompt("保存名","配置 "+new Date().toLocaleString("ja-JP",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}));if(!title)return;const list=store.get("9b_layouts");list.unshift({id:Date.now(),title,date:new Date().toISOString(),balls:structuredClone(balls),lines:structuredClone(lines),memos:structuredClone(memos)});store.set("9b_layouts",list);renderSaved();renderHome();toast("配置を保存しました")};
$("#clearSavedLayouts").onclick=()=>{if(confirm("保存した配置をすべて削除しますか？")){store.set("9b_layouts",[]);renderSaved();renderHome()}};
function renderSaved(){const list=store.get("9b_layouts"),el=$("#savedLayouts");el.innerHTML=list.length?list.map(x=>`<div class="summary-row"><div><strong>${esc(x.title)}</strong><small>${new Date(x.date).toLocaleString("ja-JP")}</small></div><button class="badge load-layout" data-id="${x.id}">開く</button></div>`).join(""):'<div class="summary-row"><strong>まだ保存はありません</strong></div>';$$(".load-layout",el).forEach(b=>b.onclick=()=>{const x=list.find(v=>String(v.id)===b.dataset.id);if(x){balls=structuredClone(x.balls||[]);lines=structuredClone(x.lines||[]);memos=structuredClone(x.memos||[]);commit();renderLayout();setZoom(1);toast("配置を読み込みました")}})}
$("#exportPng").onclick=()=>{const c=document.createElement("canvas");c.width=1200;c.height=675;const x=c.getContext("2d");x.fillStyle="#149fa2";x.fillRect(0,0,c.width,c.height);x.setLineDash([4,4]);x.strokeStyle="rgba(255,255,255,.35)";for(let i=1;i<7;i++){x.beginPath();x.moveTo(c.width*i/7,0);x.lineTo(c.width*i/7,c.height);x.stroke()}for(let i=1;i<4;i++){x.beginPath();x.moveTo(0,c.height*i/4);x.lineTo(c.width,c.height*i/4);x.stroke()}x.setLineDash([]);for(const l of lines){x.beginPath();x.moveTo(c.width*l.x1/100,c.height*l.y1/100);x.lineTo(c.width*l.x2/100,c.height*l.y2/100);x.strokeStyle="#fff";x.lineWidth=4;x.stroke()}for(const b of balls){const px=c.width*b.x/100,py=c.height*b.y/100;x.beginPath();x.arc(px,py,10,0,Math.PI*2);x.fillStyle=b.n?colors[b.n]:"#fff";x.fill()}const a=document.createElement("a");a.download="9board-layout.png";a.href=c.toDataURL();a.click()};

const toolbar=$("#layoutToolbar");let tdrag=null;toolbar.addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;tdrag={x:e.clientX,left:toolbar.scrollLeft}});toolbar.addEventListener("pointermove",e=>{if(tdrag)toolbar.scrollLeft=tdrag.left-(e.clientX-tdrag.x)});toolbar.addEventListener("pointerup",()=>tdrag=null);toolbar.addEventListener("pointercancel",()=>tdrag=null);

let score={p1:0,p2:0};$$("[data-score]").forEach(b=>b.onclick=()=>{const k=b.dataset.score;score[k]=Math.max(0,score[k]+Number(b.dataset.delta));$("#"+k+"score").textContent=score[k]});$("#resetCounter").onclick=()=>{score={p1:0,p2:0};$("#p1score").textContent=$("#p2score").textContent=0};$("#saveCounter").onclick=()=>{const list=store.get("9b_counter");list.unshift({id:Date.now(),date:new Date().toISOString(),p1:$("#p1name").value,p2:$("#p2name").value,s1:score.p1,s2:score.p2,type:$("#raceType").value});store.set("9b_counter",list);renderCounter();renderHome();toast("スコアを記録しました")};$("#clearCounterHistory").onclick=()=>{store.set("9b_counter",[]);renderCounter();renderHome()};
function renderCounter(){const list=store.get("9b_counter"),el=$("#counterHistory");el.innerHTML=list.length?list.map(x=>`<div class="summary-row"><div><strong>${esc(x.p1)} ${x.s1} - ${x.s2} ${esc(x.p2)}</strong><small>${esc(x.type)} ・ ${new Date(x.date).toLocaleString("ja-JP")}</small></div></div>`).join(""):'<div class="summary-row"><strong>まだ履歴はありません</strong></div>'}

const form=$("#matchForm");function showForm(on){form.classList.toggle("show",on)}$("#newMatchBtn").onclick=$("#newMatchText").onclick=()=>{showForm(!form.classList.contains("show"));$("#matchDate").value ||= new Date().toISOString().slice(0,10)};$("#cancelMatch").onclick=()=>showForm(false);form.onsubmit=e=>{e.preventDefault();const list=store.get("9b_matches");list.unshift({id:Date.now(),date:$("#matchDate").value,status:$("#matchStatus").value,title:$("#matchTitle").value||"無題",venue:$("#matchVenue").value,opponent:$("#matchOpponent").value,result:$("#matchResult").value,race:$("#matchRace").value,fee:$("#matchFee").value,url:$("#matchUrl").value,memo:$("#matchMemo").value});store.set("9b_matches",list);form.reset();showForm(false);renderMatches();renderHome();toast("対戦記録を保存しました")};
function renderMatches(){const list=store.get("9b_matches"),el=$("#matchList");el.innerHTML=list.length?list.map(x=>`<div class="summary-row"><div><strong>${esc(x.title)}</strong><small>${esc(x.date||"")} ${x.venue?"・"+esc(x.venue):""}${x.opponent?" ・ vs "+esc(x.opponent):""}</small></div><span class="badge">${esc(x.result||x.status)}</span></div>`).join(""):'<div class="summary-row"><strong>まだ対戦記録はありません</strong></div>'}
function renderHome(){const l=store.get("9b_layouts"),c=store.get("9b_counter"),m=store.get("9b_matches");$("#homeSummary").innerHTML=`<div class="summary-row"><strong>保存した配置</strong><span class="badge">${l.length}件</span></div><div class="summary-row"><strong>カウンター履歴</strong><span class="badge">${c.length}件</span></div><div class="summary-row"><strong>対戦記録</strong><span class="badge">${m.length}件</span></div>`}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
renderLayout();renderSaved();renderCounter();renderMatches();renderHome();applyZoom();
})();